### ISSUE TITLE
Can I get Bitmap Fonts?

### ISSUE THREAD

**Issue by bipinkrish** [sutton-signwriting/font-ttf#10]
I want these font files https://github.com/sutton-signwriting/font-ttf/tree/master/src/font in Bitmap type [FNT].

I tried [ttf2fnt.com](https://ttf2fnt.com/) but it seems not working.

**Comment by Slevinski** [comment]
Unfortunately, these fonts are not available in that format.  You can find the glyphs in PNG format in the [SignWriting 2010 Fonts project](https://github.com/Slevinski/signwriting_2010_fonts).  The fonts were created with the [SignWriting 2010 Tools project](https://github.com/Slevinski/signwriting_2010_tools).
