### ISSUE TITLE
problem with symbolSvg and fsw.symbolSize

### ISSUE THREAD

**Issue by wdiestel** [sutton-signwriting/font-ttf#11]
Hello,

I try to use `ssw.ttf.fsw.symbolSvg("S10000")` to create SVG with just one symbol, but in the beginning only an empty SVG like `<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1" height="1"></svg>` is created. Trying to debug I found that the size calculation fails. I think the issue is, that without proper initialisation in my case this piece of code draws a black sign on black background so not finding it in the imageData:

```
  const symbolSize$1 = function (id) {
    if (id in sizes) {
      return [...sizes[id]];
    }
    if (!context) {
      const canvaser = document.createElement("canvas");
      canvaser.width = bound;
      canvaser.height = bound;
      context = canvaser.getContext("2d", {
        willReadFrequently: true
      });
    }
    context.clearRect(0, 0, bound, bound);
    context.font = 30 * zoom + "px 'SuttonSignWritingLine'";
    context.fillText(String.fromCodePoint(id + 0xF0000), 0, 0);
    const imgData = context.getImageData(0, 0, bound, bound).data;
    let w, h, i, s;
    wloop: for (w = bound - 1; w >= 0; w--) {
      for (h = 0; h < bound; h += 1) {
        for (s = 0; s < 4; s += 1) {
          i = w * 4 + h * 4 * bound + s;
          if (imgData[i]) {
            break wloop;
          }
        }
      }
    }
    var width = w;
    hloop: for (h = bound - 1; h >= 0; h--) {
      for (w = 0; w < width; w += 1) {
        for (s = 0; s < 4; s += 1) {
          i = w * 4 + h * 4 * bound + s;
          if (imgData[i]) {
            break hloop;
          }
        }
      }
    }
```
Both strokeStyle and fillStyle show "#000000" in the debugger.

I'm using the version from unpkg:

```
<script src="https://unpkg.com/@sutton-signwriting/core@1.6.0"></script>
<script src="https://unpkg.com/@sutton-signwriting/core@1.6.0/fsw/fsw.js"></script>
<script src="https://unpkg.com/@sutton-signwriting/font-ttf@1.5.2/fsw/fsw.js"></script>
```

**Comment by Slevinski** [comment]
There seems to be two issues going on.  First, you need to add the CSS for the fonts.  Second, you need to make sure the fonts are loaded.  https://www.sutton-signwriting.io/font-ttf/#font

To add the CSS for the fonts, use Javascript.

    font.cssAppend()

To check when the fonts are available to use.

    const callback = () => {
      console.log("Sutton SignWriting Line and Fill fonts are ready to use")
    }
    
    font.cssLoaded( callback )

After these two steps, you will be able to calculate the size of the symbols.  You can find a code example here:  https://codesandbox.io/p/sandbox/sutton-signwriting-truetype-fonts-via-module-moceo

You can look at the code for these two functions to add however you want to your project.
* https://github.com/sutton-signwriting/font-ttf/blob/master/src/font/font-css-append.js
* https://github.com/sutton-signwriting/font-ttf/blob/master/src/font/font-css-loaded.js

I'll make sure to improve the documentation with the next version release.

**Comment by wdiestel** [comment]
Ok, now it works. I had to add the font.js in the importing, to get the ttf.font CSS/callback included:

```
<script src="https://unpkg.com/@sutton-signwriting/font-ttf@1.5.2/fsw/fsw.js"></script>
<script src="https://unpkg.com/@sutton-signwriting/font-ttf@1.5.2/font/font.js"></script>
```

Thanks for the hint!
