### ISSUE TITLE
Eager Canvas Creation - Preventing Server Side Rendering

### ISSUE THREAD

**Issue by AmitMY** [sutton-signwriting/font-ttf#2]
Hi Steve,
I'd like to perform server side rendering for my application using this library.

When importing this library (without doing anything else), the following code executes eagerly:
https://github.com/sutton-signwriting/font-ttf/blob/3a9f5cf979d4b4b204386970163f12b927eec96c/src/font/font-symbol-size.js#L4-L9

This does not work when there is no `document`.

**Comment by AmitMY** [comment]
I believe my PR addresses this - but I have not tested it. https://github.com/sutton-signwriting/font-ttf/pull/3

**Comment by Slevinski** [comment]
Thanks for the issue and the PR.  I'll check it out soon.
