### ISSUE TITLE
Regression: Module not found

### ISSUE THREAD

**Issue by AmitMY** [sutton-signwriting/font-ttf#6]
Yesterday there was a patch change that broke the following:

```ts
import {signNormalize} from '@sutton-signwriting/font-ttf/fsw/fsw';
```
> Error: Module not found: Error: Package path ./fsw/fsw is not exported from package \node_modules\@sutton-signwriting\font-ttf (see exports field in \node_modules\@sutton-signwriting\font-ttf\package.json)

```ts
import {font} from '@sutton-signwriting/font-ttf';
```
> Error: Module not found: Error: Package path ./font/font.min is not exported from package \node_modules\@sutton-signwriting\font-ttf (see exports field in \node_modules\@sutton-signwriting\font-ttf\package.json)

**Comment by Slevinski** [comment]
Thanks for the report.  I'll take a look.

**Comment by Slevinski** [comment]
The exports field in package.json needs to be updated or removed.  After a bit of research, I came up with the following.  The imports work, but the type definitions don't.  Still investigating.  I'll probably remove the package.json exports field, so I'll leave this here for future reference.

    "exports": {
        ".": {
          "types": "./core.d.ts",
          "require": "./core.min.cjs",
          "import": "./core.min.mjs",
          "default": "./core.min.js"
        },
        "./fsw/fsw": {
          "types": "./fsw/fsw.d.ts",
          "require": "./fsw/fsw.min.cjs",
          "import": "./fsw/fsw.min.mjs",
          "default": "./fsw/fsw.min.js"
        },
        "./fswquery/fswquery": {
          "types": "./fswquery/fswquery.d.ts",
          "require": "./fswquery/fswquery.min.cjs",
          "import": "./fswquery/fswquery.min.mjs",
          "default": "./fswquery/fswquery.min.js"
        },
        "./swu/swu": {
          "types": "./swu/swu.d.ts",
          "require": "./swu/swu.min.cjs",
          "import": "./swu/swu.min.mjs",
          "default": "./swu/swu.min.js"
        },
        "./swuquery/swuquery": {
          "types": "./swuquery/swuquery.d.ts",
          "require": "./swuquery/swuquery.min.cjs",
          "import": "./swuquery/swuquery.min.mjs",
          "default": "./swuquery/swuquery.min.js"
        },
        "./style/style": {
          "types": "./style/style.d.ts",
          "require": "./style/style.min.cjs",
          "import": "./style/style.min.mjs",
          "default": "./style/style.min.js"
        },
        "./convert/convert": {
          "types": "./convert/convert.d.ts",
          "require": "./convert/convert.min.cjs",
          "import": "./convert/convert.min.mjs",
          "default": "./convert/convert.min.js"
        }
      },

**Comment by Slevinski** [comment]
Another exports variation. Still not working with type definitions.

    "exports": {
      ".": {
        "require": {
          "types": "./core.d.ts",
          "default":"./core.min.cjs"
        },
        "import": {
          "types": "./core.d.ts",
          "default":"./core.min.mjs"
        },
        "default": {
          "types": "./core.d.ts",
          "default":"./core.min.js"
        }
      },

**Comment by Slevinski** [comment]
New packages are available for @sutton-signwriting/core and @sutton-signwriting/font-ttf.  I ended up removing the exports from package.json for now.  This should fix the issue.

**Comment by AmitMY** [comment]
Thanks Steve for the quick resolution! the issue is no more.

Maybe it is me who is importing them wrong, if that is the case, please let me know how I should import instead.

**Comment by Slevinski** [comment]
I'm glad the issue is solved.  I caused this issue by improperly configuring the package.json file.  Thanks for the feedback.
